dist: trusty
sudo: false
language: c
addons:
  apt:
    packages:
    - cppcheck
    - docbook-xml
    - docbook-xsl
    - libxml2-utils
    - ocaml-native-compilers
    - xsltproc
script:
- make
- make test
- make -C doc validate all
- make install PREFIX=$HOME/.local
- export PATH=~/.local/bin:"$PATH"
- brightmare --version
- export MANPATH=~/.local/share/man MANWIDTH=80
- man 1 brightmare | grep -A 10 -w BRIGHTMARE
- cppcheck --error-exitcode=1 *.c

# vim:ts=2 sts=2 sw=2 et
