version.cmo: version.cmi 
version.cmx: version.cmi 
listEx.cmo: listEx.cmi 
listEx.cmx: listEx.cmi 
strEx.cmo: strEx.cmi 
strEx.cmx: strEx.cmi 
unicore.cmo: strEx.cmi unicore.cmi 
unicore.cmx: strEx.cmx unicore.cmi 
unicode.cmo: locale.cmi strEx.cmi unicore.cmi unicode.cmi 
unicode.cmx: locale.cmi strEx.cmx unicore.cmx unicode.cmi 
unicode_html.cmo: listEx.cmi strEx.cmi unicode_html.cmi 
unicode_html.cmx: listEx.cmx strEx.cmx unicode_html.cmi 
unicode_konwert.cmo: locale.cmi strEx.cmi unicore.cmi unicode_konwert.cmi 
unicode_konwert.cmx: locale.cmi strEx.cmx unicore.cmx unicode_konwert.cmi 
dictionary.cmo: listEx.cmi strEx.cmi dictionary.cmi 
dictionary.cmx: listEx.cmx strEx.cmx dictionary.cmi 
latex_dictionary.cmo: dictionary.cmi latex_dictionary.cmi 
latex_dictionary.cmx: dictionary.cmx latex_dictionary.cmi 
decoration.cmo: decoration.cmi 
decoration.cmx: decoration.cmi 
decoration_html.cmo: decoration_html.cmi 
decoration_html.cmx: decoration_html.cmi 
render.cmo: listEx.cmi zz_signatures.cmx 
render.cmx: listEx.cmx zz_signatures.cmx 
rmath.cmo: listEx.cmi zz_signatures.cmx 
rmath.cmx: listEx.cmx zz_signatures.cmx 
automaton.cmo: automaton.cmi 
automaton.cmx: automaton.cmi 
automaton2.cmo: automaton2.cmi 
automaton2.cmx: automaton2.cmi 
tokenize.cmo: listEx.cmi strEx.cmi zz_signatures.cmx 
tokenize.cmx: listEx.cmx strEx.cmx zz_signatures.cmx 
parse.cmo: dictionary.cmi latex_dictionary.cmi listEx.cmi strEx.cmi \
    zz_signatures.cmx 
parse.cmx: dictionary.cmx latex_dictionary.cmx listEx.cmx strEx.cmx \
    zz_signatures.cmx 
brightmare.cmo: automaton.cmi decoration_html.cmi listEx.cmi locale.cmi \
    parse.cmx render.cmx rmath.cmx tokenize.cmx unicode_html.cmi 
brightmare.cmx: automaton.cmx decoration_html.cmx listEx.cmx locale.cmi \
    parse.cmx render.cmx rmath.cmx tokenize.cmx unicode_html.cmx 
unicode.cmi: zz_signatures.cmx 
unicode_html.cmi: zz_signatures.cmx 
unicode_konwert.cmi: zz_signatures.cmx 
decoration.cmi: zz_signatures.cmx 
decoration_html.cmi: zz_signatures.cmx 
latex_dictionary.cmi: dictionary.cmi 
automaton.cmi: zz_signatures.cmx 
automaton2.cmi: zz_signatures.cmx 
