listEx.cmo: listEx.cmi 
listEx.cmx: listEx.cmi 
strEx.cmo: strEx.cmi 
strEx.cmx: strEx.cmi 
dictionary.cmo: listEx.cmi dictionary.cmi 
dictionary.cmx: listEx.cmx dictionary.cmi 
latex_dictionary.cmo: dictionary.cmi latex_dictionary.cmi 
latex_dictionary.cmx: dictionary.cmx latex_dictionary.cmi 
unicore.cmo: strEx.cmi unicore.cmi 
unicore.cmx: strEx.cmx unicore.cmi 
unicore_convert.cmo: dictionary.cmi strEx.cmi unicore_convert.cmi 
unicore_convert.cmx: dictionary.cmx strEx.cmx unicore_convert.cmi 
unicode.cmo: locale.cmi strEx.cmi unicore.cmi unicode.cmi 
unicode.cmx: locale.cmi strEx.cmx unicore.cmx unicode.cmi 
unicode_html.cmo: listEx.cmi strEx.cmi unicode_html.cmi 
unicode_html.cmx: listEx.cmx strEx.cmx unicode_html.cmi 
unicode_ascii.cmo: locale.cmi strEx.cmi unicore.cmi unicore_convert.cmi \
    unicode_ascii.cmi 
unicode_ascii.cmx: locale.cmi strEx.cmx unicore.cmx unicore_convert.cmx \
    unicode_ascii.cmi 
unicode_konwert.cmo: locale.cmi strEx.cmi unicore.cmi unicode_konwert.cmi 
unicode_konwert.cmx: locale.cmi strEx.cmx unicore.cmx unicode_konwert.cmi 
decoration.cmo: decoration.cmi 
decoration.cmx: decoration.cmi 
render.cmo: listEx.cmi signatures.cmx 
render.cmx: listEx.cmx signatures.cmx 
rmath.cmo: listEx.cmi signatures.cmx 
rmath.cmx: listEx.cmx signatures.cmx 
automaton.cmo: automaton.cmi 
automaton.cmx: automaton.cmi 
automaton2.cmo: automaton2.cmi 
automaton2.cmx: automaton2.cmi 
lexscan.cmo: listEx.cmi signatures.cmx strEx.cmi 
lexscan.cmx: listEx.cmx signatures.cmx strEx.cmx 
parse.cmo: listEx.cmi parsetree.cmx signatures.cmx 
parse.cmx: listEx.cmx parsetree.cmx signatures.cmx 
interpret.cmo: listEx.cmi parsetree.cmx signatures.cmx strEx.cmi 
interpret.cmx: listEx.cmx parsetree.cmx signatures.cmx strEx.cmx 
interpret_debug.cmo: listEx.cmi parsetree.cmx signatures.cmx 
interpret_debug.cmx: listEx.cmx parsetree.cmx signatures.cmx 
brightmare.cmo: automaton.cmi decoration.cmi decoration_html.cmx \
    interpret.cmx interpret_debug.cmx latex_dictionary.cmi lexscan.cmx \
    listEx.cmi parse.cmx render.cmx rmath.cmx signatures.cmx strEx.cmi \
    unicode_ascii.cmi unicode_html.cmi version.cmx 
brightmare.cmx: automaton.cmx decoration.cmx decoration_html.cmx \
    interpret.cmx interpret_debug.cmx latex_dictionary.cmx lexscan.cmx \
    listEx.cmx parse.cmx render.cmx rmath.cmx signatures.cmx strEx.cmx \
    unicode_ascii.cmx unicode_html.cmx version.cmx 
dictionary.cmi: signatures.cmx 
latex_dictionary.cmi: signatures.cmx 
unicode.cmi: signatures.cmx 
unicode_html.cmi: signatures.cmx 
unicode_ascii.cmi: signatures.cmx 
unicode_konwert.cmi: signatures.cmx 
automaton.cmi: signatures.cmx 
automaton2.cmi: signatures.cmx 
