dictionary.cmo: dictionary.cmi 
dictionary.cmx: dictionary.cmi 
latex_dictionary.cmo: dictionary.cmi 
latex_dictionary.cmx: dictionary.cmx 
unicode.cmo: unicode.cmi 
unicode.cmx: unicode.cmi 
render.cmo: unicode.cmi 
render.cmx: unicode.cmx 
render_math.cmo: render.cmo 
render_math.cmx: render.cmx 
tokenize.cmo: tokenize.cmi 
tokenize.cmx: tokenize.cmi 
parse.cmo: dictionary.cmi latex_dictionary.cmo render.cmo render_math.cmo \
    tokenize.cmi unicode.cmi 
parse.cmx: dictionary.cmx latex_dictionary.cmx render.cmx render_math.cmx \
    tokenize.cmx unicode.cmx 
brightmare.cmo: parse.cmo render.cmo tokenize.cmi version.cmo 
brightmare.cmx: parse.cmx render.cmx tokenize.cmx version.cmx 
