#!/bin/sh
version=${1:?"no version number provided"}
set -e -x
dch -m -v "$version" -c doc/changelog
export version
perl -pi -e 's/^let version = "\K[\w.]+/$ENV{version}/' version.ml
perl -pi -e 's/<!ENTITY version '"'"'\K[\w.]+/$ENV{version}/' doc/*.xml
