#!/bin/sh
version=${1:?"no version number provided"}
set -e -x
dch -m -v "$version" -c doc/changelog
sed -i -r -e "s/^(let version) = .*/\1 = \"$version\"/" version.ml
sed -i -r -e "s/<(!ENTITY version) '[0-9.]+'>/<\1 '$version'>/" doc/*.xml
